name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  publish-code-coverage:
    if: ${{ !contains(github.event.head_commit.message, 'coverage skip') }}
    runs-on: ubuntu-latest
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Generate Coverage Report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoMergedReport

      - name: Publish Coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash
